services:
  - type: web
    name: tripleseat-revel-connector
    runtime: python3
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
