services:
  - type: web
    name: tripleseat-revel-connector
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src